create extension if not exists pgcrypto;

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  travel_class text not null check (travel_class in ('Economy', 'First Class', 'Premium')),
  travel_date date not null,
  departure text not null check (departure in ('Morning (08:00)', 'Afternoon (15:00)', 'Night (22:00)')),
  adults integer not null check (adults between 1 and 6),
  children integer not null check (children between 0 and 4),
  total_amount integer not null check (total_amount >= 0),
  payment_status text not null default 'pending' check (payment_status in ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
  status text not null default 'new' check (status in ('new', 'contacted', 'confirmed', 'completed', 'cancelled')),
  consent_to_store_personal_data boolean not null default true,
  source text not null default 'website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.passengers (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  full_name text not null,
  passport_id text not null,
  gender text not null check (gender in ('Male', 'Female')),
  country_code char(2) not null,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 80),
  rating integer not null check (rating between 1 and 5),
  route text not null default 'Madaraka Express' check (char_length(route) between 1 and 80),
  review_text text not null check (char_length(review_text) between 1 and 1200),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

create table if not exists public.review_moderation_events (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references public.reviews(id) on delete cascade,
  action text not null check (action in ('approved', 'rejected')),
  previous_status text not null check (previous_status in ('pending', 'approved', 'rejected')),
  new_status text not null check (new_status in ('approved', 'rejected')),
  moderated_at timestamptz not null default now(),
  actor text not null
);

comment on table public.passengers is 'Isolated passenger identity storage. Passport/ID fields must be deleted or anonymized within the documented retention window.';
comment on column public.passengers.passport_id is 'AES-256-GCM encrypted passport/ID envelope generated by api/bookings.ts before persistence.';
comment on table public.reviews is 'User-submitted reviews. Only rows with status approved may be displayed publicly.';
comment on table public.review_moderation_events is 'Audit log for review moderation actions. Actor is a non-secret label and must never store admin tokens.';

create index if not exists bookings_reference_idx on public.bookings(reference);
create index if not exists bookings_payment_status_idx on public.bookings(payment_status);
create index if not exists bookings_created_at_idx on public.bookings(created_at desc);
create index if not exists passengers_booking_id_idx on public.passengers(booking_id);
create index if not exists reviews_status_created_at_idx on public.reviews(status, created_at desc);
create index if not exists review_moderation_events_review_id_idx on public.review_moderation_events(review_id, moderated_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists bookings_set_updated_at on public.bookings;
create trigger bookings_set_updated_at
before update on public.bookings
for each row
execute function public.set_updated_at();

create or replace function public.create_booking(
  p_reference text,
  p_travel_class text,
  p_travel_date date,
  p_departure text,
  p_adults integer,
  p_children integer,
  p_total_amount integer,
  p_full_name text,
  p_passport_id text,
  p_gender text,
  p_country_code text,
  p_email text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking_id uuid;
begin
  insert into public.bookings (
    reference,
    travel_class,
    travel_date,
    departure,
    adults,
    children,
    total_amount,
    payment_status,
    status,
    consent_to_store_personal_data,
    source
  )
  values (
    p_reference,
    p_travel_class,
    p_travel_date,
    p_departure,
    p_adults,
    p_children,
    p_total_amount,
    'pending',
    'new',
    true,
    'website'
  )
  returning id into v_booking_id;

  insert into public.passengers (
    booking_id,
    full_name,
    passport_id,
    gender,
    country_code,
    email
  )
  values (
    v_booking_id,
    p_full_name,
    p_passport_id,
    p_gender,
    upper(p_country_code)::char(2),
    lower(p_email)
  );

  return v_booking_id;
end;
$$;

alter table public.bookings enable row level security;
alter table public.passengers enable row level security;
alter table public.reviews enable row level security;
alter table public.review_moderation_events enable row level security;

drop policy if exists reviews_deny_anon_select on public.reviews;
create policy reviews_deny_anon_select on public.reviews
for select to anon, authenticated
using (false);

drop policy if exists reviews_deny_anon_insert on public.reviews;
create policy reviews_deny_anon_insert on public.reviews
for insert to anon, authenticated
with check (false);

drop policy if exists reviews_deny_anon_update on public.reviews;
create policy reviews_deny_anon_update on public.reviews
for update to anon, authenticated
using (false)
with check (false);

drop policy if exists review_moderation_events_deny_anon_select on public.review_moderation_events;
create policy review_moderation_events_deny_anon_select on public.review_moderation_events
for select to anon, authenticated
using (false);

drop policy if exists review_moderation_events_deny_anon_insert on public.review_moderation_events;
create policy review_moderation_events_deny_anon_insert on public.review_moderation_events
for insert to anon, authenticated
with check (false);

revoke all on function public.create_booking(text, text, date, text, integer, integer, integer, text, text, text, text, text) from public;
grant execute on function public.create_booking(text, text, date, text, integer, integer, integer, text, text, text, text, text) to service_role;
